### ISSUE TITLE
Adding compatibility for the call of Cthulhu series of mods

### ISSUE THREAD

**Issue by TheEventHorizon** [AthenaSulisMinerva/CombatExtendedFastTrack#14]
This mod has been a breath of fresh air for rimworld, but I was wondering if it would possible to add support for the incredible Cthulhu series of mods found here:  https://steamcommunity.com/workshop/filedetails/?id=829619412

Thank you all for your amazing work and dedication!

**Comment by AthenaSulisMinerva** [comment]
sumghai's specialty is modern and scifi, so I'll work on this for the next release cycle.

**Comment by AthenaSulisMinerva** [comment]
# TODO List
- [ ] RoM - Vampires
- [ ] RoM - Werewolves
- [ ] RoM - Arachnophobia
- [ ] CoC - Elder Things
- [ ] CoC - Factions - Items Only
- [ ] CoC - Factions
- [ ] CoC - Cults
- [ ] CoC - Cosmic Horrors
- [ ] H.P. Lovecraft Storyteller

Holy shit, @TheEventHorizon - this list is huge!

**Comment by TheEventHorizon** [comment]
> # TODO List
> * [ ]  RoM - Vampires
> * [ ]  RoM - Werewolves
> * [ ]  RoM - Arachnophobia
> * [ ]  CoC - Elder Things
> * [ ]  CoC - Factions - Items Only
> * [ ]  CoC - Factions
> * [ ]  CoC - Cults
> * [ ]  CoC - Cosmic Horrors
> * [ ]  H.P. Lovecraft Storyteller
> 
> Holy shit, @TheEventHorizon - this list is huge!

There are two (partial) patched for [RoM - Cults](https://steamcommunity.com/sharedfiles/filedetails/?id=1357970120) [Source](https://github.com/Saebbi/ROM-Cults-CE-Patch) and [RoM - Cosmic Horrors](https://steamcommunity.com/sharedfiles/filedetails/?id=1357967363&searchtext=cosmic+horrors) [Souce](https://github.com/Saebbi/Rim-of-Madness-Cosmic-Horrors-CE-Patch). I say partial because neither fully patch the section of RoM they claim too. But I just wanted to link them here incase you would like some reference material. I hope this is helpful!

**Comment by AthenaSulisMinerva** [comment]
Hey, thanks - that would be a good starting point.

I also edited your comment to remove the quote, because that's a dynamic todo-list.

**Comment by TheEventHorizon** [comment]
> Hey, thanks - that would be a good starting point.
> 
> I also edited your comment to remove the quote, because that's a dynamic todo-list.

Run into any difficult objects to patch? I'm extremely novice when it comes to programming but I'm more than happy to help in any way I can.

**Comment by AthenaSulisMinerva** [comment]
It just takes time to sit down and systematically plan out which items to patch and how, and whether some patches can be consolidated at the start.

**Comment by TheEventHorizon** [comment]
Any possibility of this getting a patch?

**Comment by AthenaSulisMinerva** [comment]
We're currently busy with the post-1.6 cleanup, updating existing ammo defs and patches to work with 1.6's new armor penetration system.

Also, these are a series of rather large race/faction packs, which were not easy to patch in back in CE 1.5, and certainly more difficult in 1.6 now that we have to account for the new systems too. In contrast, gun packs are quicker and easier to patch, so @sumghai for instance will focus on tackling that sort of low-lying fruit.

We'll get around to this eventually, but the team's triple-booked with other higher-priority issues.

If you wish to see CoC/RoM mods get patched faster, feel free to work with us in developing the patches.

**Comment by Totherphoenix** [comment]
Has there been any update on this patch post-1.6-release?
