### ISSUE TITLE
Chicken Plucker's Rimmu-Nation & Red Horse Mods - Batch 3

### ISSUE THREAD

**Issue by sumghai** [AthenaSulisMinerva/CombatExtendedFastTrack#200]
In no particular order of precedence:

- [x] (CP) Metal Gear Solid (1.0)
  - [x] Apparel_Armor
  - [x] Apparel_Armor_Headgear
  - [x] Apparel_Headgear
  - [x] Apparel_OnSkin
  - [x] MeleeWeapon
  - [x] PawnKindDefs
  - [x] RangedIndustrial_Pistols
  - [x] RangedIndustrial_R_Bullpup_Style
  - [x] Scenario
- [x] (CP) Spec Ops - The Line (1.0)
  - [x] Apparel_Armor
  - [x] Apparel_Armor_Headgear
  - [x] Apparel_Backpacks
  - [x] Apparel_Headgear
  - [x] Apparel_OnSkin
  - [x] PawnKindDefs
  - [x] RangedIndustrial_LMG
  - [x] RangedIndustrial_M_BoltAction
  - [x] RangedIndustrial_R_AR_Style
  - [x] RangedIndustrial_SF_Pack
  - [x] RangedSpecial_AirSupport
  - [x] Scenario
- [x] (RH) Cordis Die (1.0)
  - [x] Apparel_Armor
  - [x] Apparel_Armor_Headgear
  - [x] Apparel_Headgear
  - [x] Apparel_OnSkin
  - [x] Bodies_Mechanical
  - ~~Bodies_Quadcopter~~ _Not required due to low armor_
  - [x] BodyParts_Mechanical
  - ~~BodyParts_Quadcopter~~ _Not required due to low armor_
  - [x] PawnKinds
  - [x] Races_Mechanical
  - [x] Races_Quadcopter
  - [x] RangedIndustrial_BigGuns
  - [x] RangedIndustrial_HRT_Pack
  - [x] RangedIndustrial_LMG
  - [x] RangedIndustrial_M_BoltAction
  - [x] RangedIndustrial_M_DMR
  - [x] RangedIndustrial_QuadcopterMG
  - [x] RangedIndustrial_R_AK_Style
  - [x] RangedIndustrial_R_Bullpup_Style
  - [x] RangedIndustrial_R_Others
  - [x] RangedIndustrial_Shotguns
  - [x] RangedIndustrial_SMG
  - [x] RangedIndustrial_TankGuns
- [x] DOOM (1.0) (See #113)
  - [x] Apparel_Armor
  - [x] Apparel_Armor_Headgear
  - [x] LauncherDOOM_Weapons
  - [x] MeleeDOOM_Weapons
  - [x] RangedDOOM_Weapons
  - [x] CE Ammo Def: UAC BFG Cell (Plasma)
  - [x] CE Ammo Def: UAC EMG Cell (Plasma) - projectile only variant for infinite-ammo EMG Pistol
  - [x] CE Ammo Def: UAC EMG Cell (Plasma) - craftable ammo for EMG Mk V Pistol
  - [x] CE Ammo Def: UAC Plasma Cell (Plasma) + 4 projectile variants
  - [x] CE Ammo Def: UAC Rocket Mk VI (HE)
- [x] DOOM Kit - Classic (1.0)
  - [x] Apparel_Armor
  - [x] Apparel_Armor_Headgear
  - [x] LauncherDOOM_Weapons
  - [x] MeleeDOOM_Weapons
  - [x] RangedDOOM_Weapons
  - [x] CE Ammo Def: 4 double-barreled projectile variants of standard 12 Gauge shotgun shells
  - [x] CE Ammo Def: UAC Energy Cell (Plasma) + 2 projectile variants
  - [x] CE Ammo Def: UAC Rocket Mk I(HE)
- [x] WWII Soviet Faction (1.0)
  - [x] PawnKindDefs
  - [x] Clothing
  - [x] Headgear
  - [x] RangedIndustrial
  - [x] Turret
  - [x] CE Ammo Def: 762x385R Cannon Shell (HE/EMP)
- [x] (RH) Last Man Mercs
  - [x] **Rename to [RH] Last Man Contingent** (#217)
  - [x] Regression checking for all existing LMM/LMC patches (#217)
  - [x] MeleeWeapon - RNMeleeWeapon_Knife_Shiv (#217)
  - [x] Apparel_Armor - RNApparel_HVYArmor_LMCT (#217)
  - [x] Apparel_Armor_Headgear - RNApparel_FASTHelmetLMCT (#217)
- [x] (RH) Umbra Company
  - [x] Rebalance and consolidate apparel patches
  - [x] Add BTR-70 APC with KPV HMG turret (#219) 
- [x] (RH) The Ghosts
  - [x] Rebalance and consolidate apparel patches
- [x] (RH) Task Force 141
  - [x] Rebalance and consolidate apparel patches
- [x] (RH) Militaires Sans Frontieres
  - [x] Rebalance and consolidate apparel patches
- [x] (RH) Elite Crew
  - [x] Rebalance and consolidate apparel patches
  - [x] Add RGD-5 thrown grenade ammo
  - [x] Add Bomber pawn type
- [x] Rimmu-Nation - Clothing
  - [x] Rebalance and consolidate apparel patches
- [x] Red Horse Furniture
  - [x] Rebalance and consolidate apparel patches (#223)
  - [x] Add new FBI apparel (#223)
  - [x] Add new FBI HRT weapons (#223)
- [ ] Rebalance primary and sidearm magazine ammo capacity for all CP / RN / RH faction pawns (partial fix for #227) 

The subitems in this list will be added/updated as required

**Comment by AthenaSulisMinerva** [comment]
You absolute madlad!

Best of luck with the patching - I'll see if I can tackle one of the other issues during Xmas break.

**Comment by skycrossercat** [comment]
Uhm…I am making a WWII Soviet Faction patch right now, only thing left is the Zis-3 turret patch and its new shell def. It may take some more time to get it done cause I am not actually a modder. If you want to take over it, I can submit the part I done so far and let you check they are usable or not.
Currently done: PawnKind, Apparel_Clothing, Apparel_Headgear, RangeIndustrial

**Comment by sumghai** [comment]
That would be awesome, @skycrossercat! Please do send us your WIP.

**Comment by sumghai** [comment]
Alright, first one through the gate is (CP) Metal Gear Solid (1.0)!

**Comment by skycrossercat** [comment]
https://drive.google.com/open?id=1oS0G4MWPQ2nRLzCopJMgql_4lFdl8D8W

The parts I've done are all here, they work fine in my test, hope this would help.

**Comment by sumghai** [comment]
For balance reasons, we should definitely recalculate the crafting stats to CE:FT standards.

Thanks for your hard work! I'm downloading it now, and will work on that right after Spec Ops: The Line is done.

**Comment by sumghai** [comment]
(CP) Spec Ops - The Line (1.0) is now done!

As promised, @skycrossercat, I'm going to jump right into WWII Soviet Faction (1.0) first thing after work tomorrow.

**Comment by sumghai** [comment]
For the ZiS cannon from WWII Soviet Faction, I will need to define a new 762x385R Cannon Shell ammo and projectile type (with HE, HEAT and EMP* variants)

*EMP shells did not exist in WWII, but the lore for the WWII Soviet Faction mod describes the faction as being founded by a lost Cosmonaut who convinced the local RimWorlders to adopt Soviet-style Communism; therefore, we'll treat this faction as essentially Soviet re-enactors, and add EMP shells for the sake of completeness.

**Comment by sumghai** [comment]
WWII Soviet Faction patches are good to go! 

Special thanks to @skycrossercat - I only needed to make minor tweaks to your existing patches, as well as add a patch for the ZiS-3 Divisional Gun turret.

I've also created the new 76.2x385mmR Cannon Shell ammo definitions, along with unique artwork.

**Comment by sumghai** [comment]
Well bugger, guess I have to also fix and rename the LMM patches to LMC too.

**Comment by sumghai** [comment]
I had to invoke some major cross-referencing fuckery of multiple issues, but I've added commits for the BTR-70 APC updates to [RH] Umbra Company, as well as consolidating and updating apparel patches to now include soft apparel like hats and fatigues.

**Comment by Jalordon** [comment]
What is the intended power level of RH/CP armors?

From personal experience playing with the current patching values, it feels that the added armors are very powerful; comparable to or slightly stronger than composite armor from the base CE FT mod, which is able to resist rifle caliber AP ammo.

However, composite armor has only MaxHitPoints of 75, and CE FT patches armor values to correlate to current health of armor,
(In Patches\Core\Stats\Stats.xml)
```
<li Class="StatPart_Health">
			  <curve>
			    <points>
			      <li>(0.0, 0.0)</li>
			      <li>(0.5, 0.5)</li>
			      <li>(0.8, 1.0)</li>
			    </points>
			  </curve>
			</li>
```
Composite armor does a good job at stopping the first few rounds that hit it, but it rapidly degrades and loses protection effectiveness.

Currently CP/RH patching does nothing to touch MaxHitPoints of the armors so not only are they very protective, but they also provide consistently high protection under constant gunfire and it is difficult to over power anyone in said armors.

Would it be possible to also touch MaxHitPoints, and evaluate what power level the various armors are meant to be? Again I don't know the intended armor strength, but most things seem to currently be composite armor strong.

**Comment by sumghai** [comment]
@Jalordon, please start a new, separate issue for your suggestion.

**Comment by AthenaSulisMinerva** [comment]
@sumghai - How far are you from finishing this?

**Comment by sumghai** [comment]
@AthenaSulisMinerva - I'm up to the last mod of this batch (DOOM 1.0).

This and DOOM Kit - Classic are taking much longer than usual, because I have to come up with exotic damage types and new ammo definitions, instead of having real-life ammo and stats to work with.

After this, I've got to do one last pass for grenadier pawn ammo count (at the request of @skycrossercat) before I can definitively call this one done.

**Comment by sumghai** [comment]
DOOM is finally done. Gosh, that was unpleasant.

The only thing left to do now is rebalancing the primary magazine ammo capacity of grenadier pawns from all the factions, and then we can wrap this up for good.

**Comment by sumghai** [comment]
@skycrossercat - I am now extending the scope of the pawn inventory ammo rebalance to all faction pawns, as well as try to add sidearms.

**Comment by skycrossercat** [comment]
@sumghai You mean you want handle the sidearm parts on your end as well?

**Comment by sumghai** [comment]
@skycrossercat - Yup, I might as well do so while I'm at it.

On my local development copy of CE:FT, I've (so far) updated half of all the faction pawns with the new ammo and sidearm spawning:

* 95~98% of pawns will reliably spawn with a primary weapon, a sidearm and sufficient ammo for both

* The remaining 1~2% is due to edge cases where a pawn is equipped with a primary weapon that is far too bulky, leaving little to no room for a sidearm

* I have slightly buffed some of the vests and backpacks to have improved carrying capacity, but I don't want to give them ridiculously OP values

* @ChickenPluckers's faction pawns also tend to carry a massive amount of MREs, medkits and drugs, far more than faction pawns by other modders. I've had to modify CE:FT's Core patches to reduce drug bulk (#216) and jury-rig many of the faction patches to reduce the meals/medkits that the pawns carry in their inventory, but that is not 100% reliable

* For grenadiers, many third-party faction mods patched for CE specify 10\~30 grenades, but this doesn't account for grenade launchers with multiple-round capacity; for RH faction pawns, I consulted [a US Army report on infantry loadouts](https://drive.google.com/open?id=1xo-slAF6WDIePRHmwZLTH0nGuCQ16m8M), which usually recommends 24\~24 40 mm grenades, and then decided to assess each pawntype on a case-by-case basis:

  * For pawns armed with a China Lake Grenade Launcher (3 rd capacity), I went for a **magazine count** of 4~5, since 3 x 5 = 15, and I want to leave bulk/weight capacity for the backup sidearm and ammo

  * For pawns armed with a RPG-7 (1 rd capacity), I also went for 4\~5; in practice, CE RPG rockets vary greatly in weight and bulk, so pawns might actually carry anywhere between 4\~5 Frag rockets to 1\~2 HEAT rockets, and might actually not have any room left for carry a sidearm

  * For pawns armed with 40 mm grenade launchers, if it is a single-barrel single-shot-then-reload weapon like the M302, I will set the **magazine count** to 10\~30 or 20\~24; if it is a multiple-shot weapon like the Milkor MGL, then I will set the mag count down to 4\~5

  * For pawns armed with hand grenades, I'll limit them to 4~5 grenades as well, because IRL it simply isn't practical to have 10 or 20 hand grenades dangling off one's chest harness, as well as leaving room for the backup sidearm and ammo; in practice, this works out quite nicely in-game, with grenadiers switching to handguns once they've thrown all their grenades

In the meantime, feel free to work on the shield spawning, since AFAIK none of the RH faction pawns are purely melee, and so don't carry shields.

**Comment by sumghai** [comment]
Addendum - Not all faction pawns will get sidearms, as some factions don't come with faction-appropriate sidearms in the first place (and I'm loathe to assign them generic CE sidearms).

**Comment by sumghai** [comment]
This is _**finally**_ done.
